/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 phantoms.glb --transform 
Files: phantoms.glb [6.41MB] > /Users/jini.choi/Documents/jini/3d_gsap_test/public/models/robot/phantoms-transformed.glb [192.39KB] (97%)
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Robot(props) {
  //경로 수정
  const { nodes, materials } = useGLTF(
    "./models/robot/phantoms-transformed.glb"
  );

  // useEffect(() => {
  //   console.log(nodes);
  //   console.log(nodes.Cube001.Cube003);
  // }, []);
  useEffect(() => {
    Object.keys(nodes).forEach((key) => {
      console.log(key); // 모든 노드의 키 출력
    });
  }, []);

  return (
    <group {...props} dispose={null}>
      {/* <mesh
        geometry={nodes.Cylindre005.geometry}
        material={nodes.Cylindre005.material}
        position={[-0.017, 2.754, -0.066]}
        rotation={[-Math.PI, 0, 0]}
        scale={0.582}
      /> */}
      <group
        position={[-0.214, 0.163, 0.365]}
        rotation={[0, -0.152, 0]}
        scale={0.146}
      >
        <mesh geometry={nodes.Cube003.geometry} material={materials.Metal}>
          <meshPhysicalMaterial
            color="#aaa"
            roughness={0.2}
            metalness={1}
            reflectivity={0.5}
            iridescence={0.3}
            iridescenceIOR={1}
            iridescenceThicknessRange={[100, 100]}
          />
        </mesh>
        {/* <mesh geometry={nodes.Cube003.geometry} material={materials.Metal} /> */}
      </group>
    </group>
  );
}

useGLTF.preload("./models/robot/phantoms-transformed.glb");
